### PR TITLE
Prefix DoQ packets with length as per rfc9250

### LINKED ISSUE #257: error-----failed to decode query
I see such an error message through the systemctl status routedns command.

```
Aug 15 23:09:46 idns routedns[18131]: time="2022-08-15T23:09:46+08:00" level=error msg="failed to decode query" addr=":8053" client="ip address:40080" error="dns: bad rdata" id=local-doq protocol=doq
Aug 15 23:09:46 idns routedns[18131]: time="2022-08-15T23:09:46+08:00" level=error msg="failed to decode query" addr=":8053" client="ip address:34424" error="dns: bad rdata" id=local-doq protocol=doq
Aug 15 23:09:46 idns routedns[18131]: time="2022-08-15T23:09:46+08:00" level=error msg="failed to decode query" addr=":8053" client="ip address:36051" error="dns: bad rdata" id=local-doq protocol=doq
Aug 15 23:09:46 idns routedns[18131]: time="2022-08-15T23:09:46+08:00" level=error msg="failed to decode query" addr=":8053" client="ip address:36051" error="dns: bad rdata" id=local-doq protocol=doq
Aug 15 23:09:46 idns routedns[18131]: time="2022-08-15T23:09:46+08:00" level=error msg="failed to decode query" addr=":8053" client="ip address:36051" error="dns: bad rdata" id=local-doq protocol=doq
Aug 15 23:09:47 idns routedns[18131]: time="2022-08-15T23:09:47+08:00" level=error msg="failed to decode query" addr=":8053" client="ip address:38873" error="dns: bad rdata" id=local-doq protocol=doq
Aug 15 23:09:47 idns routedns[18131]: time="2022-08-15T23:09:47+08:00" level=error msg="failed to decode query" addr=":8053" client="ip address:43486" error="dns: bad rdata" id=local-doq protocol=doq
Aug 15 23:09:47 idns routedns[18131]: time="2022-08-15T23:09:47+08:00" level=error msg="failed to decode query" addr=":8053" client="ip address:43486" error="dns: bad rdata" id=local-doq protocol=doq
Aug 15 23:09:47 idns routedns[18131]: time="2022-08-15T23:09:47+08:00" level=error msg="failed to decode query" addr=":8053" client="ip address:43486" error="dns: bad rdata" id=local-doq protocol=doq
Aug 15 23:09:48 idns routedns[18131]: time="2022-08-15T23:09:48+08:00" level=error msg="failed to decode query" addr=":8053" client="ip address:41596" error="dns: bad rdata" id=local-doq protocol=doq



```

### PR DESCRIPTION
**Pull request by folbricht**
Add length prefix to all DoQ queries/responses as per RFC.

Fixes #257

### CODE REVIEW

**Review by charlieporth1 — COMMENTED** [review]
Shouldn't this change for DoH3 too @folbricht or am I wrong about that

**Comment by charlieporth1** [comment]
@folbricht ping!

**Comment by folbricht** [comment]
Hmm, I don't believe it does. That should just be regular DoH but sent over QUIC so I don't believe the prefix is required. I should test that with a DOH3 resolver

**Comment by charlieporth1** [comment]
> 

Looks like it does work with a doh3 resolver works just file. Tested with https://play.google.com/store/apps/details?id=com.frostnerd.smokescreen&hl=en_US&gl=US

**Pull request merged**
