### PR TITLE
Honor query timeout in udp/tcp resolvers

### LINKED ISSUE #318: Bootstrap resolver doesn't obbey the timeout set with query-timeout when the resolver is a plain resolver with hostname
This is easy to reproduce:

Bootstrap address is blocked by iptables for testing: `sudo iptables -A OUTPUT -p tcp -d 208.67.222.222 --dport 443 -j DROP`

==============

Config 1:

```
[bootstrap-resolver]
address = "208.67.222.222:443"
protocol = "tcp"

[resolvers.manual]
address = "https://dns.nextdns.io/dns-query"
protocol = "doh"
query-timeout = 10

[listeners.local-udp-ipv4]
address = "127.0.0.1:1053"
protocol = "udp"
resolver = "manual"
```

Result:

```
$ time host -p 1053 g.co 127.0.0.1
;; communications error to 127.0.0.1#1053: timed out
;; communications error to 127.0.0.1#1053: timed out
;; no servers could be reached

real	0m10.029s
user	0m0.005s
sys	0m0.005s
```

/\ Query timeout is obeyed.

===============

```
[bootstrap-resolver]
address = "208.67.222.222:443"
protocol = "tcp"

[resolvers.manual]
address = "one.one.one.one:53"
protocol = "tcp"
query-timeout = 10

[listeners.local-udp-ipv4]
address = "127.0.0.1:1053"
protocol = "udp"
resolver = "manual"
```

Result:

```
$ time host -p 1053 g.co 127.0.0.1
Using domain server:
Name: 127.0.0.1
Address: 127.0.0.1#1053
Aliases: 

Host g.co not found: 2(SERVFAIL)

real	0m2.022s
user	0m0.008s
sys	0m0.004s
```

/\ Query timeout is ignored.

### PR DESCRIPTION
**Pull request by folbricht**
Fixes #318

### CODE REVIEW

**Comment by alpominth** [comment]
```
$ /dev/shm/routedns tmp.toml 
INFO[0000] starting listener                             addr="127.0.0.1:1053" id=local-udp-ipv4 protocol=udp
ERRO[0006] failed to open connection                     addr="208.67.222.222:443" error="dial tcp 208.67.222.222:443: i/o timeout"
ERRO[0008] failed to open connection                     addr="208.67.222.222:443" error="dial tcp 208.67.222.222:443: i/o timeout"
ERRO[0010] failed to open connection                     addr="208.67.222.222:443" error="dial tcp 208.67.222.222:443: i/o timeout"
ERRO[0012] failed to open connection                     addr="one.one.one.one:53" error="dial tcp: lookup one.one.one.one on [::1]:53: query for 'one.one.one.one.' timed out"
ERRO[0012] failed to open connection                     addr="208.67.222.222:443" error="dial tcp 208.67.222.222:443: i/o timeout"
ERRO[0012] failed to resolve                             addr="127.0.0.1:1053" client=127.0.0.1 error="dial tcp: lookup one.one.one.one on [::1]:53: query for 'one.one.one.one.' timed out" id=local-udp-ipv4 protocol=udp qname=g.co.
ERRO[0014] failed to open connection                     addr="208.67.222.222:443" error="dial tcp 208.67.222.222:443: i/o timeout"
ERRO[0016] failed to open connection                     addr="208.67.222.222:443" error="dial tcp 208.67.222.222:443: i/o timeout"
ERRO[0018] failed to open connection                     addr="208.67.222.222:443" error="dial tcp 208.67.222.222:443: i/o timeout"
ERRO[0019] failed to resolve                             addr="127.0.0.1:1053" client=127.0.0.1 error="query for 'g.co.' timed out" id=local-udp-ipv4 protocol=udp qname=g.co.
ERRO[0020] failed to open connection                     addr="one.one.one.one:53" error="dial tcp: lookup one.one.one.one on [::1]:53: query for 'one.one.one.one.' timed out"
ERRO[0020] failed to open connection                     addr="208.67.222.222:443" error="dial tcp 208.67.222.222:443: i/o timeout"
```

Config:

```
[bootstrap-resolver]
address = "208.67.222.222:443"
protocol = "tcp"

[resolvers.manual]
address = "one.one.one.one:53"
protocol = "tcp"
query-timeout = 10

[listeners.local-udp-ipv4]
address = "127.0.0.1:1053"
protocol = "udp"
resolver = "manual"
```

Result:

```
$ time host -p 1053 g.co 127.0.0.1
;; communications error to 127.0.0.1#1053: timed out
;; communications error to 127.0.0.1#1053: timed out
;; no servers could be reached


real	0m10.028s
user	0m0.007s
sys	0m0.002s
```

I also tested `query-timeout` in `bootstrap` section:

```
$ /dev/shm/routedns tmp.toml 
INFO[0000] starting listener                             addr="127.0.0.1:1053" id=local-udp-ipv4 protocol=udp
ERRO[0005] failed to open connection                     addr="one.one.one.one:53" error="dial tcp: lookup one.one.one.one: i/o timeout"
ERRO[0005] failed to resolve                             addr="127.0.0.1:1053" client=127.0.0.1 error="query for 'g.co.' timed out" id=local-udp-ipv4 protocol=udp qname=g.co.
ERRO[0006] failed to open connection                     addr="208.67.222.222:443" error="dial tcp 208.67.222.222:443: i/o timeout"
ERRO[0008] failed to open connection                     addr="208.67.222.222:443" error="dial tcp 208.67.222.222:443: i/o timeout"
ERRO[0010] failed to open connection                     addr="208.67.222.222:443" error="dial tcp 208.67.222.222:443: i/o timeout"
ERRO[0012] failed to open connection                     addr="208.67.222.222:443" error="dial tcp 208.67.222.222:443: i/o timeout"
```

Config:

```
[bootstrap-resolver]
address = "208.67.222.222:443"
protocol = "tcp"
query-timeout = 2

[resolvers.manual]
address = "one.one.one.one:53"
protocol = "tcp"
query-timeout = 1

[listeners.local-udp-ipv4]
address = "127.0.0.1:1053"
protocol = "udp"
resolver = "manual"
```

Result:

```
$ time host -p 1053 g.co 127.0.0.1
Using domain server:
Name: 127.0.0.1
Address: 127.0.0.1#1053
Aliases: 

Host g.co not found: 2(SERVFAIL)

real	0m1.021s
user	0m0.004s
sys	0m0.006s
```

==============================================

It's ready to merge.

Thanks

**Review by charlieporth1 — APPROVED** [review]

**Comment by alpominth** [comment]
This bootstrap address 208.67.222.222:443 is valid with port 443:

```
$ host resolver1.opendns.com
resolver1.opendns.com has address 208.67.222.222
resolver1.opendns.com has IPv6 address 2620:119:35::35

$ host resolver2.opendns.com
resolver2.opendns.com has address 208.67.220.220
resolver2.opendns.com has IPv6 address 2620:119:53::53
```

These resolvers using port 443 (TLS port) and TCP are specially made for situations when only ports 80/443 are allowed by the firewall and there is no UDP connectivity (good for Tor).

It would be a good idea to use these TCP port 443 resolvers as a fallback/default resolvers in case the resolvers in /etc/resolv.conf are unreachable, this could be implemented as default in RouteDNS. Just a suggestion.

**Comment by cbuijs** [comment]
You can use the "Fail-Rotate group" for this?

**Comment by alpominth** [comment]
@cbuijs

I cannot, but it's due to a new bug I've discovered right now:

`sudo iptables -A OUTPUT -p tcp -d 208.67.222.222 --dport 443 -j DROP`

```
[bootstrap-resolver]
address = "208.67.222.222:443"
protocol = "tcp"

[resolvers.cf]
address = "one.one.one.one:53"
protocol = "tcp"
query-timeout = 10

[groups.manual]
resolvers = ["cf"]
type = "fail-rotate"

[listeners.local-udp-ipv4]
address = "127.0.0.1:1053"
protocol = "udp"
resolver = "manual"
```

```
$ time host -p 1053 g.co 127.0.0.1
;; communications error to 127.0.0.1#1053: timed out
;; communications error to 127.0.0.1#1053: connection refused
;; no servers could be reached


real	0m5.024s
user	0m0.009s
sys	0m0.000s
```

```
$ /opt/routedns/routedns ./tmp.toml 
INFO[0000] starting listener                             addr="127.0.0.1:1053" id=local-udp-ipv4 protocol=udp
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xae33ed]

goroutine 20 [running]:
github.com/txthinking/socks5.(*Client).DialWithLocalAddr(0x0, {0xc00012a8a6, 0x3}, {0x0, 0x0}, {0xc000140150, 0x12}, {0x0?, 0x0})
	/home/user/go/pkg/mod/github.com/txthinking/socks5@v0.0.0-20230325130024-4230056ae301/client.go:43 +0x8d
github.com/txthinking/socks5.(*Client).Dial(0x7f3429adea68?, {0xc00012a8a6?, 0x0?}, {0xc000140150?, 0x0?})
	/home/user/go/pkg/mod/github.com/txthinking/socks5@v0.0.0-20230325130024-4230056ae301/client.go:36 +0x34
github.com/folbricht/routedns.GenericDNSClient.Dial({{0xd624e0, 0x0}, {0xc00012a8a6, 0x3}, 0xc000170600, {0x0, 0x0, 0x0}}, {0xc000140150, 0x12})
	/dev/shm/routedns-issue-264/dnsclient.go:129 +0x442
github.com/folbricht/routedns.(*Pipeline).start(0xc0001498c0)
	/dev/shm/routedns-issue-264/pipeline.go:90 +0x192
created by github.com/folbricht/routedns.NewPipeline
	/dev/shm/routedns-issue-264/pipeline.go:48 +0x16b

```

@folbricht 

I've used this branch (SOCKS5 one): https://github.com/folbricht/routedns/pull/317

go version go1.20.5 linux/amd64

**Comment by folbricht** [comment]
@alpominth That issue was related to the socks5 implementation. I couldn't reproduce it with your config, but changed something that may have fixed it. Also, that branch does not cleanly merge with the query timeout changes in this PR. I'm going to have to do that manually

**Comment by alpominth** [comment]
@folbricht I've tested the master branch because I wanted to test if fail-rotate could work as a query-timeout in named DNS resolvers.

I also tested the SOCKS5 branch for the bug I said above, no problems.

I could see that the problem with query-timeout option and named DNS resolvers was fixed in the SOCKS5 branch.

**Pull request merged**
