### PR TITLE
Update configuration.md

### PR DESCRIPTION
**Pull request by charlieporth1**
Better documatation for `reset-after` clairifying usage.

### CODE REVIEW

**Comment by folbricht** [comment]
So the way this works is that if there's a failure in the preferred resolver this immediately switches to a failover resolver. Then, after `reset-after` seconds have passed, the group switches back to using the preferred resolver, not actually the next one in the list. It's the time it'll use alternative resolver before it resets back to the first. How about something like this? Not sure if that's more clear though:

`Time in seconds before switching from an alternative resolver back to the preferred resolver (first in the list) , default 60. Note: This is not a timeout argument. After a failure of the preferred resolver, this defines the amount of time to use alternative/failover 
resolvers before switching back to the preferred.`

**Comment by charlieporth1** [comment]
> So the way this works is that if there's a failure in the preferred resolver this immediately switches to a failover resolver. Then, after `reset-after` seconds have passed, the group switches back to using the preferred resolver, not actually the next one in the list. It's the time it'll use alternative resolver before it resets back to the first. How about something like this? Not sure if that's more clear though:
> 
> `Time in seconds before switching from an alternative resolver back to the preferred resolver (first in the list) , default 60. Note: This is not a timeout argument. After a failure of the preferred resolver, this defines the amount of time to use alternative/failover resolvers before switching back to the preferred.`

I do like that more. Is there a limit of 2 to the number of resolvers? Or If you have more than 2 will It pass on to the next one like in my config 
```
# Order matters
[groups.ctp-dns-fail-back]
resolvers = [
        "ctp-dns-group",
        "ctp-dns-fail-rotate",
        "ctp-dns_nginx-back-up-group-fail-back",
        "ctp-dns-failover-backup",
]
reset-after = 128
type = "fail-back"
servfail-error = true

[groups.ctp-dns-fail-rotate]
resolvers = [
        "ctp-dns_group-fastest-home-external",
        "ctp-dns_group-fastest-aws-external",
        "ctp-dns_group-fail-rotate-home",
        "ctp-dns_group-fail-rotate-aws",
        "ctp-dns_group-fail-back-home",
        "ctp-dns_group-fail-back-aws",
]
type = "fail-rotate"
servfail-error = true
```

**Comment by folbricht** [comment]
Yes, you can have more than one, and those are specified in order of preference basically. Imagine you had a list of resolvers like so

```
[r0, r1, r2, r3,...]
```

In this case, r0 is the "preferred" resolver. If r0 fails, the group switches to r1, if that one fails it moves on to r2 and so on. After the reset interval expires, r0 becomes the active resolver again. So it always starts with r0, and then moves further one step on failure, and starting from the beginning again after the given time.

**Review by folbricht — APPROVED** [review]
Thank you

**Pull request merged**
