### PR TITLE
Allow blocklist loader to fail on startup

### PR DESCRIPTION
**Pull request by folbricht**
Implements #153

### CODE REVIEW

**Comment by cbuijs** [comment]
Works as expected.

**Comment by charlieporth1** [comment]
@cbuijs If you could test this that would be great! I'll submit it for review as well

**Comment by cbuijs** [comment]
Merge with Issue #153, right?
https://github.com/folbricht/routedns/tree/issue-153

**Comment by cbuijs** [comment]
Build ends with an error:

```
config.go:1:1: expected 'package', found '<<'
../../cache.go:1:1: expected 'package', found '<<'
```

**Comment by charlieporth1** [comment]
@cbuijs Just to verify your running this commit [da2dc29](https://github.com/folbricht/routedns/pull/259/commits/da2dc296f40a87c0c79695c7b75ffc34876b373f) right?

**Comment by cbuijs** [comment]
@charlieporth1 

Yes, used [da2dc29](https://github.com/folbricht/routedns/commit/da2dc296f40a87c0c79695c7b75ffc34876b373f) and reverted to [4321645](https://github.com/folbricht/routedns/commit/4321645a6d4aa0154ef78249847138e0a5cd9dc1) to make it build again.

**Comment by charlieporth1** [comment]
@cbuijs If you could try these mod tidy changes that would be great!

**Comment by cbuijs** [comment]
Seems that there are some conflicts when using it together with issue-214 and/or prefetch-3, on caching related code. When I don't apply these, the build works and the load errors don't kill routedns anymore.

**Comment by folbricht** [comment]
The vendoring shouldn't be necessary, let's remove this again as all that does is make PRs harder to read.

**Comment by charlieporth1** [comment]
@folbricht this one should be ready for review.

**Comment by charlieporth1** [comment]
@folbricht should be good to go. Switched the go version to 1.18.

**Comment by charlieporth1** [comment]
@cbuijs ping!

**Comment by charlieporth1** [comment]
I ran this with a `http 403` result and it worked

**Comment by charlieporth1** [comment]
I ran this with a `http 403` result and it worked @folbricht  @cbuijs  if one of you could test that would be great

**Comment by cbuijs** [comment]
Tested and looks like it loads when a url/blocklist cannot load on start.

**Comment by folbricht** [comment]
Looks good to merge I think

**Pull request merged**
