### PR TITLE
Add logging to ecs-modifier

### PR DESCRIPTION
**Pull request by cbuijs**
Shows what ecs-modifier did/does.

### CODE REVIEW

**Comment by cbuijs** [comment]
Tested and works. See logging snippet taken in #210.

**Comment by cbuijs** [comment]
Just as heads-up @folbricht

**Comment by folbricht** [comment]
I believe this has been superseded by https://github.com/folbricht/routedns/pull/213, @cbuijs Do you agree?

**Comment by cbuijs** [comment]
> I believe this has been superseded by #213, @cbuijs Do you agree?

Yes, this one (#212) became redundant.

**Comment by cbuijs** [comment]
Resolved by #213.

**Pull request closed without merging**
