### PR TITLE
Support routing by time and weekday

### PR DESCRIPTION
**Pull request by folbricht**
Implements #158

### CODE REVIEW

**Comment by charlieporth1** [comment]
This will be a fantastic feature that I am looking forward to. I was going to implement this on my own servers using bash because I need this.

**Comment by folbricht** [comment]
Just out of interest, do you have a specific use-case in mind for this? Is it also about routing to different blocklists based on the time of day or something more interesting? Just wondering if I should make an example for it and add to the docs.

**Comment by charlieporth1** [comment]
> Just out of interest, do you have a specific use-case in mind for this? Is it also about routing to different blocklists based on the time of day or something more interesting? Just wondering if I should make an example for it and add to the docs.

I run a private DNS server on Google cloud and in order to save money with that I turn it off using another DNS server at home which they tend to use each other in failover events. When the Google cloud server shuts off I would like to route the traffic specially locally instead of the reduced topology I currently have that causes issues wth resolving

**Comment by folbricht** [comment]
Thanks, interesting use-case. This PR is almost ready to go, just need a bit more documentation.

**Pull request merged**
